export enum SlideType {
  BRIDGE = "BRIDGE",
  CHORUS = "CHORUS",
  INTRO = "INTRO",
  OUT = "OUT",
  PRE = "PRE",
  SOLO = "SOLO",
  VERSE = "VERSE",
}

export enum ChordActionType {
  ADD_CHORD_C = 'ADD_CHORD_C',
  ADD_CHORD_D = 'ADD_CHORD_D',
  ADD_CHORD_E = 'ADD_CHORD_E',
  ADD_CHORD_F = 'ADD_CHORD_F',
  ADD_CHORD_G = 'ADD_CHORD_G',
  ADD_CHORD_A = 'ADD_CHORD_A',
  ADD_CHORD_B = 'ADD_CHORD_B',
  MOD_CHORD_SHARP = 'MOD_CHORD_SHARP',
  MOD_CHORD_MIN = 'MOD_CHORD_MIN',
  MOD_CHORD_DIM = 'MOD_CHORD_DIM',
  MOD_CHORD_AUG = 'MOD_CHORD_AUG',
  OPT_CHORD_SUS = 'OPT_CHORD_SUS',
  OPT_CHORD_7 = 'OPT_CHORD_7',
  OPT_CHORD_2 = 'OPT_CHORD_2',
  DEL_CHORD_DEL = 'DEL_CHORD_DEL',
  DEL_CHORD_BS = 'DEL_CHORD_BS',
}